### ISSUE TITLE
iOS permissions issue

### ISSUE THREAD

**Issue by MydusApps** [morenoh149/react-native-contacts#765]
Permissions promise is not completing, nor is it triggering a permissions request on the device for iOS 18. All the correct permissions have been stated in the Info.plist. This was working in previous versions.

Please let me know if you require any additional info to resolve this.

**Comment by C0zmaCatalin** [comment]
I am experiencing this issue as well. The code works perfectly on versions lower than 18.0. However, on versions 18.0 and above, neither the then nor the catch block executes, and no console log is printed.

`Contacts.checkPermission()
    .then((permission) => {
        console.log(permission);
    })
    .then((err) => {
        console.log(err);
    });`

**Comment by MydusApps** [comment]
A work around we have found is to use react-native-permissions to request permissions from the user and then use react-native-contacts to retrieve the contact data. I hope this helps.

**Comment by tanayzepto** [comment]
I am experiencing the same issue; has anyone found a solution?

**Comment by Kushagra-ag** [comment]
Facing the same issue on 18.3.1

> A work around we have found is to use react-native-permissions to request permissions from the user and then use react-native-contacts to retrieve the contact data. I hope this helps.

This worked for me.

**Comment by x64Eddie** [comment]
Hi @Kushagra-ag and @MydusApps, just curious, do you all remember if it reproduced 100% of the time in any iOS 18+ ? I am debugging a similar issue, but I can't seem to repro this issue on my personal iOS v18.3.1 device. Thank you!

**Comment by morenoh149** [comment]
Not sure what the issue is

**Comment by vvroul** [comment]
Currently having the same issue, on iOS 18.4, RN 0.79.2 and release 8.0.5, calling 
```Contacts.checkPermission().then((permission) => {})``` won't trigger the promise 
and can't even log the permission var.  Also worked for me in previous versions.

**Comment by Lewitje** [comment]
Same issue here, I see the: NSContactsUsageDescription in the info.plist but doesn't it get triggered.

**Comment by captnseagraves** [comment]
Same issue. Contacts.checkPermission() hangs when called and never completes.

**Comment by xansrakshit** [comment]
> A work around we have found is to use react-native-permissions to request permissions from the user and then use react-native-contacts to retrieve the contact data. I hope this helps.

Did any1 resolved it? 

I can't use react-native-permissions latest version as it requires xcode 16 to make the ios builds, but i'm targeting ios12+ builds.....i thought this library had a work around for this limited contact's permission check issue (feature in ios18+), but it too has a bug.

Tested this on ios 18.4 simulator (xcode 16.2)

**Comment by trizerr** [comment]
It was fixed in this [pull request](https://github.com/morenoh149/react-native-contacts/pull/771/commits/88dc09a4b7f19cbd827307dc41edc98fe10162e8), but I see it didn't get released yet.

Basically method which check permission doesn't have a resolve call if ios version is greater than 18.0.
After applying a patch with this change, issue was fixed for me

![Image](https://github.com/user-attachments/assets/e4654eb3-55e3-4c95-ad6d-31854a06151e)

**Comment by technoch1ef** [comment]
@trizerr `Contacts.checkPermission()` still hangs for me and never resolves, even though this code is present in 8.0.5

<img width="1137" height="822" alt="Image" src="https://github.com/user-attachments/assets/9f7cb6c0-79d9-4ddc-87cf-9090cc1bf788" />

And `Contacts.requestPermission()` returns undefined, even though I've set limited access in settings 😔
