### ISSUE TITLE
AddContact not working on Android

### ISSUE THREAD

**Issue by basdvries** [morenoh149/react-native-contacts#85]
![image](https://cloud.githubusercontent.com/assets/7907049/18085209/77f05438-6eaa-11e6-964e-578c3c5cd1d5.png)

When calling

``` es
const phoneBookContact = {
        familyName: "",
        middleName: "",
        givenName: this.state.name,
        emailAddresses: [{
          label: "",
          email: "",
        }],
        phoneNumbers: [{
          label: "mobile",
          number: this.state.phoneNumber,
        }],
        thumbnailPath: "",
      };
      Contacts.addContact(phoneBookContact, (err) => {
        console.log('err:', err);
        Logger.logException(err);
      });
```

_Harry_: ftfy

**Comment by morenoh149** [comment]
that's very odd. The offending line is https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L70 interesting it's able to grab the `number` off the `phoneNumber[i]` object, but fails on fetching the `label`. Try throwing a debugger or println above line 70 inside that loop.

**Comment by basdvries** [comment]
You can't simulate the error? I'm testing on Android 6.0.0.
I haven't ever touched Java and I'm not familiar with the IDE (which sucks btw), and my println is not showing up?? I don't have the time to dive into this right now.
It could have something to do with memory allocation. Maybe the map is not strongly referenced? Anyway, I forked it for now and ducktaped it with an ugly try/catch block.

**Comment by morenoh149** [comment]
submit the try/catch as a PR for review. I'm not getting paid for this and I'm not very good at java either ;)

**Comment by vangberg** [comment]
This is the code in `ContactsManager.java` causing the problem:

```java
      for(int i=0; i < numOfPhones; i++) {
        phones[i] = phoneNumbers.getMap(i).getString("number");
        String label = phoneNumbers.getMap(i).getString("label");
        phonesLabels[i] = mapStringToPhoneType(label);
      }
```

The issue is that `getMap()` pops the item out of the array[1], so the second time `getMap()` is called, it is null. This has been fixed in React Native master[2]. It should be included in the upcoming 0.33 release.

[1] https://github.com/facebook/react-native/issues/8557
[2] https://github.com/facebook/react-native/commit/9a5d3bacb99275e952619ab142f4381008d13d89

**Comment by Proberts** [comment]
As of React Native 0.37 this bug/behavior in getMap() still exists - maybe it's not a bug?

For a work-around, you can change the emailAddresses and phoneNumbers handlers in ContactsManager.java to use getMap(0) instead of getMap(i)

**Comment by hanpanpan200** [comment]
I'm using ReactNative@0.38.0, and I still got this error.

I have checked the source code of React Native, and the commit [facebook/react-native@9a5d3ba](https://github.com/facebook/react-native/commit/9a5d3bacb99275e952619ab142f4381008d13d89) already fixed in 0.38.0 version.

I don't know what's wrong with it now..

Anyone has a good idea for that?
